---

- name: Get blender python executable path
  become: true
  ansible.builtin.command:
    cmd: "{{ blender_executable }} --background --python-expr 'import sys; print(sys.executable)'"
  register: blender_python
  changed_when: false

# Note assuming the apth is always on the first
- name: Set Blender Python path fact
  ansible.builtin.set_fact:
    blender_builtin_python_path: "{{ blender_python.stdout_lines[0] }}"

- name: Install pip module dependency
  become: true
  ansible.builtin.package:
    name:
      - python3-packaging
      - python3-setuptools
    state: present

- name: Ensure Blender dev virtualenv exists with latest pip
  become: true
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{ blender_venv_path }}"
    virtualenv_command: "{{ blender_builtin_python_path }} -m venv"

- name: Install blender dev packages
  become: true
  loop: "{{ blender_python_modules }}"
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ blender_venv_path }}"

...
